import { Github, Linkedin, Mail, Twitter } from 'lucide-react';
import type { Icon } from 'lucide-react';

export interface Project {
  title: string;
  description: string;
  image: string;
  hint: string;
  url: string;
  tags: string[];
}

export interface Profile {
  name: string;
  bio: string;
  contact: {
    email: string;
  };
  skills: string[];
  socials: {
    name: string;
    url: string;
    icon: Icon;
  }[];
}

export const profileData: Profile = {
  name: "Alex Doe",
  bio: "A passionate Full Stack Developer with a love for creating dynamic and beautiful web applications. I turn ideas into reality with code.",
  contact: {
    email: "alex.doe@example.com",
  },
  skills: ["React", "Next.js", "TypeScript", "Node.js", "GraphQL", "Firebase", "Tailwind CSS"],
  socials: [
    { name: "GitHub", url: "https://github.com", icon: Github },
    { name: "LinkedIn", url: "https://linkedin.com", icon: Linkedin },
    { name: "Twitter", url: "https://twitter.com", icon: Twitter },
  ],
};

export const projectsData: Project[] = [
  {
    title: "E-commerce Platform",
    description: "A full-featured e-commerce website built with Next.js, Stripe for payments, and a custom CMS for product management. Features include product search, filtering, and user authentication.",
    image: "https://placehold.co/1280x720.png",
    hint: "online store",
    url: "#",
    tags: ["Next.js", "Stripe", "TypeScript", "E-commerce"],
  },
  {
    title: "Task Management App",
    description: "A collaborative task management tool with real-time updates using Firebase. Users can create projects, assign tasks, and track progress with an intuitive drag-and-drop interface.",
    image: "https://placehold.co/1280x720.png",
    hint: "team collaboration",
    url: "#",
    tags: ["React", "Firebase", "Real-time", "Productivity"],
  },
  {
    title: "Portfolio Website",
    description: "This very portfolio website, designed to showcase my skills and projects. Built with Next.js and Tailwind CSS, featuring a dynamic background generated by AI.",
    image: "https://placehold.co/1280x720.png",
    hint: "personal website",
    url: "#",
    tags: ["Next.js", "GenAI", "Tailwind CSS"],
  },
  {
    title: "Data Visualization Dashboard",
    description: "An interactive dashboard for visualizing complex datasets using Recharts and React. Allows users to explore data through various chart types and dynamic filtering.",
    image: "https://placehold.co/1280x720.png",
    hint: "analytics chart",
    url: "#",
    tags: ["React", "Recharts", "Data Viz"],
  },
];
